config/routes.rb
Rails.application.routes.draw do
  # get 'translatioins/edit'
  # get 'translatioins/update'
  namespace :admin do
    resources :posts
  end

  scope '(:locale)', locale: /en|zh-TW/ do
    resources :posts
  end
  resources :translations, only: [:index, :edit, :update]
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/post.rb
class Admin::Post < Post

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  extend Mobility
  translates :title, type: :string,  locale_accessors: [:en, :"zh-TW"]
  translates :body, type: :text, locale_accessors: [:en, :"zh-TW"]

end

app/models/translation.rb
class Translation < ApplicationRecord
  def self.select_key(key)
    where(key: key)
  end
  # why .self when it is used as instance method?

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @admin_posts = Admin::Post.all
  end

  def show
  end

  def new
    @admin_post = Admin::Post.new
  end

  def edit
  end

  def create
    @admin_post = Admin::Post.new(post_params)
    if @admin_post.save
      redirect_to admin_posts_path
    else
      render :new
    end
  end

  def update
    if @admin_post.update(post_params)
      redirect_to admin_posts_path
    else
      render :eidt
    end
  end

  def destroy
    @admin_post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @admin_post = Admin::Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:admin_post).permit(:title, :body, :title_en, :body_en, :"title_zh_tw", :"body_zh_tw")
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :set_locale

  def set_locale 
    I18n.locale = :"zh-TW"
  end
  # def default_url_options(options = {})
    
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale
 
  def default_url_options(options = {})
    { locale: I18n.locale }
  end

  private
  # def set_locale
  #   I18n.locale = params[:locale] || I18n.default_locale
  # end
  def set_locale
    if params[:locale]
      I18n.locale = normalize_locale(params[:locale])
    elsif params[:locale].blank?
      I18n.locale = extract_locale_from_accept_language_header
    else
      I18n.default_locale
    end
  end
 
  def extract_locale_from_accept_language_header
    case request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    when 'zh'
      :"zh-TW"
    else
      :en
    end
  end

  def normalize_locale(locale)
    case locale
    when 'zh-TW'
      :"zh-TW"
    else
      :en
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  # def new
  #   @post = Post.new
  # end

  # # GET /posts/1/edit
  # def edit
  # end

  # # POST /posts
  # # POST /posts.json
  # def create
  #   @post = Post.new(post_params)

  #   respond_to do |format|
  #     if @post.save
  #       format.html { redirect_to @post, notice: 'Post was successfully created.' }
  #       format.json { render :show, status: :created, location: @post }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  # def update
  #   respond_to do |format|
  #     if @post.update(post_params)
  #       format.html { redirect_to @post, notice: 'Post was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @post }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /posts/1
  # # DELETE /posts/1.json
  # def destroy
  #   @post.destroy
  #   respond_to do |format|
  #     format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  def index
    @indexing = Translation.where(locale: "zh-TW")
    @translates = Translation.all
    @translations = Translation.all
    @groups = Translation.all.group_by(&:key).to_a.first.second
    # @translations = Translation.all.group_by(&:key).to_a.first.second
  end

  def edit
    @translation = Translation.group_by(&:key)
  end

  def update
    translation = Translation.find_by(id: params[:id])
    translation.update(translation_params)
    redirect_to translations_path
  end

  private
  def translation_params
    params.require(:translation).permit(:locale, :key, :value)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/admin/posts/_form.html.erb
<%#= form_for admin_post do |f| %>
  <div class="field">
    <%#= f.label :title %>
    <%#= f.text_field :"title" %>
  </div>

  <div class="field">
    <%#= f.label :body %>
    <%#= f.text_area :body %>
  </div>

  <div class="actions">
    <%#= f.submit %>
  </div>
<% #end %>

<%= form_for admin_post do |f| %>
  <% I18n.available_locales.each do |locale| %>
    <div>
      <% title = "title_#{Mobility.normalize_locale(locale)}" %>
      <% body  = "body_#{Mobility.normalize_locale(locale)}" %>
      <%= f.label title %>
      <%= f.text_field title %>
      <%= f.label body %>
      <%= f.text_area body %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', admin_post: @admin_post %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('posts.index.posts') %></h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Edit', edit_admin_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_admin_post_path %>

app/views/admin/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form', admin_post: @admin_post %>

<%= link_to 'Back', admin_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Active</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('posts.index.posts') %></h1>
<h2><%= t('posts.index.h2') %></h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_admin_post_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/translations/index.html.erb
<h1>Translation Table</h1>

<table>
  <tbody>
   <!-- TODO: print out all the key first and use that as argument to create groups -->

    <% @translations.each do |translation| %>
      <tr>
        <td><%= translation.locale %></td>
        <td><%= form_for translation do |f| %>
            <%= f.text_field :value %>
            <%= f.submit %>
            <% end %>
        </td>
      </tr>
    <% end %> 
  </tbody>
</table>

<% @indexing.each do |t| %>
  <%= t.key %>
  <%# Translation.where(key: t.key).each do |translate| %>
  <%# Translation.select_key(t.key).each do |translate| %>
  <% @translations.select_key(t.key).each do |translate| %>
    <%= form_for translate do |f| %>
    <%= f.text_field :value %>
    <%= f.submit %>
    <% end %>
  <% end %>
<% end %>